stages:
  - build
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

default:
  image: maven:3.9.6-amazoncorretto-11
  tags:
    - mvn-java
  cache:
    paths:
      - .m2/repository/
      - target/

build:
  stage: build
  script:
    - echo Build job started
    - mvn -DskipTests clean package
    - echo ls -l target
    - ls -l target
    - echo Build job completed
  artifacts:
    paths:
      - target/*.jar
  only:
    - master
  tags:
    - itmolabs

test:
  stage: test
  script:
    - echo Test job started
    - mvn test
    - echo Test job completed
  needs:
    [ "build" ]
  only:
    - master
  tags:
    - itmolabs
