stages:
  - build
  - test
  - sonarqube-check
  - push
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: 14881488
  POSTGRES_HOST_AUTH_METHOD: trust
  SONAR_HOST_URL: "${SONAR_HOST_URL}"
  SONAR_TOKEN: "${SONARQUBE_TOKEN}"


default:
  image: maven:3.9.6-amazoncorretto-11
  tags:
    - mvn-java
  cache:
    paths:
      - .m2/repository/
      - target/
  services:
    - postgres

build:
  stage: build
  script:
    - echo Build job started
    - mvn -DskipTests clean package
    - echo ls -l target
    - ls -l target
    - echo Build job completed
  artifacts:
    paths:
      - target/*.jar
  only:
    - lab4
  allow_failure: true
  tags:
    - itmolabs

test:
  stage: test
  script:
    - echo Test job started
    - mvn test
    - echo Test job completed
  allow_failure: true
  needs: [ ]
  only:
    - lab4
  tags:
    - itmolabs

sonarqube-check:
  stage: sonarqube-check
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - mvn verify sonar:sonar -Dmaven.test.skip -Dsonar.ws.timeout=300
  allow_failure: true
  only:
    - lab4
  needs:
    [ ]
  tags:
    - itmolabs

push:
  stage: push
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [ "" ]
  script:
    - cd devops_app-backend-master
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/devops_app-backend-master"
      --dockerfile "${CI_PROJECT_DIR}/devops_app-backend-master/Dockerfile"
      --destination "cr.yandex/${REGISTRY_ID}/backend-devops_app-backend-master:${CI_COMMIT_SHORT_SHA}"
      --destination "cr.yandex/${REGISTRY_ID}/backend-devops_app-backend-master:latest"
  only:
    - lab4
  needs:
    [ "build" ]
  tags:
    - itmolabs

deploy:
  stage: deploy
  image: alpine/k8s:1.29.4
  script:
    - export K8S_BASE_URL=${K8S_BASE_URL} && export K8S_CA_DATA=${K8S_CA_DATA} && export K8S_USER_TOKEN=${K8S_USER_TOKEN}
    - cd deployment
    - kubectl rollout restart deployment devops_app-backend-master -n default
  needs:
    [ "push" ]
  only:
    - lab4
  tags:
    - itmolabs